appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: nBP/NkH4ZGWuAa1U/xDnFjIp7Ffcov+QLF3IjND618WaNZjiAom98YrhGd50M3OtzY8NC0Tg6rSzF5RWGdPqXNcoLzYbHKEQrXsv8aoDYdgAlLrT5OlVL45bpSHFFjUSCbge8ohHIemnS2UdYkiTI0Ulqw/9VCpqLzO5LZXHVNzgRoUioE+up1JmRvf0Xbs0Ync7/yUaZ40BH6sOaB6ouhD9u7CBzuLBe/H/u3BAlaZQCCldnMwVCgmj/qEMnXetb8wTNJLOPnd5ASDqxlu2L0+Wa2c88PjXHbSKn8aeuP3tXRakItJ8/n3ezH877Yn3Tyn/uBr18gyTGJAM+KdLElxWO8f2fhDK+I2rta1TB/WCf+XdEQw9rUzFYczbi1GStfb+FUzomjE03GyXThaXzhiwAhBcEhvsDJ/KbuFoJZ61I2jmO6EGYnybo5YGB4xCAgtkMYmgYJyndlHzza8pTOMxjh65t0VgYaYciicS1672usjX+rUfncMFNy/TfADluFGEVlZg2wGgbTZJ2izhwveLcrdKZXlut+SwCdBruVPIdJWWJRgLbmz0ojG/P3V+Su3fYAfWkSjKHkfGFv+kWDQeeOjxWfA7Aeo9YdTrkWREYvX04BLZQJJA/kmXR31ZhCVjFWghsy/d2Dy4AajAPkDQHN2WpLbrBlR8r8s/7Xk=
